mvc/Controllers/AlumnoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using mvc.Data;
using mvc.Models;

namespace mvc.Controllers
{
    public class AlumnoController : Controller
    {
        private AplicationContext _context;

        public AlumnoController( AplicationContext context){
            _context = context;
        }

    
        [HttpGet]
        public async Task<ActionResult> Index(){
            return _context.Alumnos != null ? 
            View(await _context.Alumnos.ToListAsync()) :
            Problem ("No se encontraron alumnos");
        }

        public IActionResult Crear()
        {
            return View();
        }

        public async Task<ActionResult> Detalle(int? id){
            if(id == null || _context.Alumnos == null ){
                return NotFound();
            }
            var alumno = await _context.Alumnos.FirstOrDefaultAsync(p => p.Id == id);
            if(alumno == null){
                return NotFound();
            }
            return View(alumno);
        }

        [HttpPost]
        public async Task<ActionResult> Crear(Alumno alumno){
            if(ModelState.IsValid){
                _context.Add(alumno);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(alumno);
        }

        [HttpGet]
        public async Task<ActionResult> Editar(int? id){
            if(id == null || _context.Alumnos == null ){
                return NotFound();
            }
            var alumno = await _context.Alumnos.FirstOrDefaultAsync(p => p.Id == id);
            if(alumno == null){
                return NotFound();
            }
            return View(alumno);
        }

        [HttpPost]
        public async Task<ActionResult> Editar(int id, Alumno alumno){
            if(id != alumno.Id){
                return NotFound();
            }
            if(ModelState.IsValid){
                _context.Update(alumno);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(alumno);
        }

        public IActionResult Eliminar(int? id){
            if(id == null){
                return NotFound();
            }
            var alumno = _context.Alumnos.FirstOrDefault(m => m.Id == id);
            if(alumno == null){
                return NotFound();
            }
            _context.Alumnos.Remove(alumno);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

    }
}

mvc/Controllers/PersonaController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using mvc.Data;
using mvc.Models;

namespace mvc.Controllers
{
    public class PersonaController : Controller
    {
        private AplicationContext _context;
        public PersonaController(AplicationContext context)
        {
            _context = context;
        }

        //Get Personas
        public async Task<ActionResult> Index(){
            return _context.Personas != null ? 
            View(await _context.Personas.ToListAsync()) :
            Problem ("No se encontraron personas");
        }

        //Get Personas/Crear
        public IActionResult Create()
        {
            return View();
        }     

        //Post Personas/Crear
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Persona persona){
            
            if(ModelState.IsValid){
                _context.Add(persona);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(persona);
        }
        
        //Get Personas/Editar/1
        public async Task<ActionResult> Edit(int? id){
            if(id == null || _context.Personas == null ){
                return NotFound();
            }
            var persona = await _context.Personas.FirstOrDefaultAsync(p => p.Id == id);
            if(persona == null){
                return NotFound();
            }
            return View(persona);
        }

        //Post Personas/Editar/1
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, Persona persona){
            if(id != persona.Id){
                return NotFound();
            }
            if(ModelState.IsValid){
                try{
                    _context.Update(persona);
                    await _context.SaveChangesAsync();
                }catch(DbUpdateConcurrencyException){
                    if(!PersonaExists(persona.Id)){
                        return NotFound();
                    }else{
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(persona);
        }


        //Get Personas/Detalles/1
        public async Task<ActionResult> Details(int? id){
            if(id == null || _context.Personas == null ){
                return NotFound();
            }
            var persona = await _context.Personas.FirstOrDefaultAsync(p => p.Id == id);
            if(persona == null){
                return NotFound();
            }
            return View(persona);
        }

        //Get Personas/Eliminar/1
        public async Task<ActionResult> Delete (int? id){
            if(id == null || _context.Personas == null ){
                return NotFound();
            }
            var persona = await _context.Personas.FirstOrDefaultAsync(p => p.Id == id);
            if(persona == null){
                return NotFound();
            }
            return View(persona);
        }

        //Post Personas/Eliminar/1
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id){
            var persona = await _context.Personas.FindAsync(id);
            if(persona == null){
                return NotFound();
            }
            _context.Personas.Remove(persona);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PersonaExists(int id){
            return _context.Personas.Any(p => p.Id == id);
        }
        
    }
}

mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - mvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/mvc.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">mvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Persona" asp-action="Index">Lista de Personas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Persona" asp-action="Create">Registrar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Alumno" asp-action="Index">Lista de Alumnos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - mvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>