scaffolding_logueo/Controllers/CuentaController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace scaffolding_logueo.Controllers
{
    public class CuentaController: Controller
    {   
        private UserManager<IdentityUser> _userManager;
        private SignInManager<IdentityUser> _signInManager;
        public CuentaController(UserManager<IdentityUser> um, SignInManager<IdentityUser> sim ){
            _userManager = um;
            _signInManager = sim;
        }

        public IActionResult Registro(){
            return View();
        }

        [HttpPost]
        public IActionResult Registro(string correo, string usuario, string password, string password2){
            if(password != password2){
                ModelState.AddModelError("password", "Las contraseñas no coinciden");
                return View();
            }
            var identityUser = new IdentityUser(usuario);
            identityUser.Email = correo;
            var result = _userManager.CreateAsync(identityUser, password).Result;
            
            if(result.Succeeded){
                return RedirectToAction("Index", "Home");
            }
            foreach(var error in result.Errors){
                ModelState.AddModelError("", error.Description);
            }
            return View();
        }

        public IActionResult Login(){
            return View();
        }

        [HttpPost]
        public IActionResult Login(string usuario, string password){
            var result = _signInManager.PasswordSignInAsync(usuario, password, false, false).Result;
            if(result.Succeeded){
                return RedirectToAction("Index", "Home");
            }

            ModelState.AddModelError("usuario" , "Usuario o contraseña incorrectos");

            return View();
        }

        public IActionResult OpcionesAdmin(){
            return View();
        }

        public async Task<IActionResult> Logout(){
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
    }
}

scaffolding_logueo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - scaffolding_logueo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/scaffolding_logueo.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">scaffolding_logueo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if(User.Identity.IsAuthenticated){
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Cuenta" asp-action="Logout">Cerrar Sesión (@User.Identity.Name)</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Cuenta" asp-action="OpcionesAdmin">Opciones Administrador</a>
                            </li>
                        }else{
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Cuenta" asp-action="Registro">Registro</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Cuenta" asp-action="Login">Iniciar Sesión</a>
                            </li>
                            
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - scaffolding_logueo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>